apiVersion: batch/v1
kind: Job
metadata:
  name: quest-smoke-test
spec:
  template:
    spec:
      containers:
      - name: quest
        image: ghcr.io/parseablehq/quest:main
        command: ["./main.sh", "smoke",  "http://parseable.parseable.svc.cluster.local", "admin", "admin"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: quest-load-test
spec:
  template:
    spec:
      containers:
      - name: quest
        image: ghcr.io/parseablehq/quest:main
        command: ["./main.sh", "load",  "http://parseable.parseable.svc.cluster.local", "admin", "admin"]
      restartPolicy: Never
  backoffLimit: 4